Fix the case of multiple table on the same page
Meteor-Community-Packages/meteor-tabular pull request #442
Opened 2021-12-23 14:46 UTC by dokithonon

When multiple table on the same page, the filter is wrong

2022-01-23 22:40 UTC, StorytellerCZ requested changes

2022-01-23 22:40 UTC, StorytellerCZ commented on client/main.js
> +              replaceSearchLabel(TAPi18n.__("Filter"));
TAP i18n is not dependency of this project, so this will not work. Please revert these sections for now. This is something for another PR.

2022-01-24 06:22 UTC, dokithonon commented
@StorytellerCZ hello, thanks for your review, I have now used table.i18n instead of TAPi18n. Thanks

2023-01-06 09:21 UTC, StorytellerCZ approved these changes

2023-10-06 11:35 UTC, merged